### ISSUE TITLE
Broken for Home Assistant 2021.6

### ISSUE THREAD

**Issue by maorcc** [maorcc/citymind_water_meter#17]
This integration does not work with Home Assistant 2021.6. 
The following error is showing up in the log:

`[custom_components.citymind_water_meter.managers.entity_manager] Failed to update, step: Start updating domain sensor, Error: 'sensor', Line: 167`

**Comment by elad-bar** [comment]
Works for me, can you please post logs (with debug level)

Thanks

**Comment by elad-bar** [comment]
@maorcc, checked it once again, I'm running v1.0.0, 
so most probably it is related to v1.0.1 changes

**Comment by Fannangir** [comment]
Same issue here.

Logger: custom_components.citymind_water_meter.managers.entity_manager
Source: custom_components/citymind_water_meter/managers/entity_manager.py:424
Failed to update, step: Start updating domain sensor, Error: 'sensor', Line: 167
V1.0.1

**Comment by maorcc** [comment]
@elad-bar, did you upgrade Home Assistant to 2021.6?
Before I created the Citimind v1.0.1 release, it didn't load on 2021.6 because there was no version attribute in the manifest file.  That's why I created the v1.0.1 release.
I am not sure what's the cause of the new error.  Maybe related to the minor changes that were done recently.  @yuvalabou, can you have a look too?

**Comment by Fannangir** [comment]
Yes I did, HA 2021.6

**Comment by elad-bar** [comment]
@maorcc, i'm on 2021.6 + 1.0.0 (with local version key change) and it works, most probably changes of 1.0.1 led to it, will try to check it during the weekend

**Comment by theone11** [comment]
I have the same error when running 1.0.1 on HA 2021.5.5

**Comment by rotem925** [comment]
I have the same issue with 1.0.1 and 2021.6
It seems broken on 2021.6

**Comment by rotem925** [comment]
Just fixed it by rolling back to version 1.0.0, and setting the version manually in the manifest.json file.

**Comment by yuvalabou** [comment]
https://github.com/maorcc/citymind_water_meter/pull/18

**Comment by elad-bar** [comment]
Fixed in v1.0.2 by @yuvalabou, please update if it works,
thanks

**Comment by yuvalabou** [comment]
Working as expected
![image](https://user-images.githubusercontent.com/3170485/120915732-260e1b80-c6ae-11eb-96ad-77eed41ae403.png)
