### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by niraviry** [maorcc/citymind_water_meter#19]
Hi.
Just moved to the new version. The Readme shows XXXXX as part of the sensor. I guess it is the meter S/N but I am not sure.
 Please update the readme file.

**Comment by maorcc** [comment]
The XXXXXXXX represents the MeterID ( מספר המונה )

Readme.md was fixed in commit 6f29234f2824f4dcc320e8dbdcef76ffb86f62fc.

**Comment by niraviry** [comment]
Thanks.

Already figured it out. It is working OK.

בתאריך יום א׳, 15 באוג׳ 2021, 01:05, מאת Maor ***@***.***>:
