### ISSUE TITLE
API PRO not working for Tel Aviv (Mei Avivim)

### ISSUE THREAD

**Issue by idodov** [maorcc/citymind_water_meter#31]
Last worked version: 1.05

It seems that Mei Avivim (מי אביבים) for Tel Aviv residents are not part of the new API (also Tel Aviv is not available via the new citymind mobile app, only through the website (the old API)).

After installation, the integration broke. Needed to restore HA backup to get access back to the meter sensors, after trying to reinstall again - there wes no way to login back. An error icon with no message appears. 
Only backup restore solved the problem for me.

**Comment by elad-bar** [comment]
You don't need to pull backup just reinstall the previous version, the citymind old portal is going to stop wotking by end of year

**Comment by idodov** [comment]
Thanks for the quick response.
I tried also to reinstall 1.05 version before the backup restore and got unknown error (red [!] without text).

**Comment by elad-bar** [comment]
Can you please post log with debug log level?

Thanks

**Comment by idodov** [comment]
Checked with ARAD customer service and they approved that Mei Avivim is not part of the new API (only the old one, not to new users), and indeed by the end of this year they will shoutdown the old API. So, unfortunately there is no bypass, and I need to stick with the working 1.05 version and not upgrade until ARAD kill the old API (or Mei Avivim will open the service to there customers).

TEL Aviv residents soon will not have access to citymind website services, even those who have active account on citymind website now.

It's a bummer.

**Comment by elad-bar** [comment]
Thanks for the update

**Comment by idodov** [comment]
I got response from Mei Avivim that said they will open the new API for there customers (Tel Aviv residents) in a few days!

**Comment by elad-bar** [comment]
Opened a discord channel to discuss any topic related to the integration:
https://discord.gg/PmDkEsepc5
