### ISSUE TITLE
issues after upgrade to v 2.0.1

### ISSUE THREAD

**Issue by shaylami** [maorcc/citymind_water_meter#32]
Hi after upgrade the integration broke i have removed the integration and also removed from HACS 
reinstall it again now getting issue to login
i have checked my login in HARAD page login and all good.
any idea?
BTW the error is only red raw without any info.

**Comment by shaylami** [comment]
![image](https://user-images.githubusercontent.com/3138264/196037504-711d0a89-0700-4e2e-b56b-3f3e5d0eac09.png)

**Comment by maorcc** [comment]
I had the exact same problem when I used the password from the old city-mind website.

Register to the new website, and login with the new password. 😊

**Comment by shaylami** [comment]
Hi Maor,

 

Can you send link to the new website?

I am registered to this one 

https://cp.city-mind.com/

 

if needed to register to a new site need to add this in the GitHub documentation.

 

Thanks ,

Shay 😉

**Comment by shaylami** [comment]
Shay Lami would like to recall the message, "[maorcc/citymind_water_meter]
issues after upgrade to v 2.0.1 (Issue #32)".

**Comment by maorcc** [comment]
The new website where you need to sign up is https://rym-pro.com/

![image](https://user-images.githubusercontent.com/255973/196058047-71437625-a870-438b-b139-a7c841da6cbd.png)

**Comment by shaylami** [comment]
Hi,

I have registered to the new site its better to update this in the github page.

 

Thanks, I will try the integration now after registration

**Comment by shaylami** [comment]
hi after register to the new site all is working 
need to update the GitHub page with the new url and guidance
thanks close

**Comment by maorcc** [comment]
@shaylami, It is likely that others will counter the same issue.

I suggest adding a clear explanation message when authentication fails.  The message should explain about the new website, and that users need to register there with a new password even if they used the old site before.

**Comment by elad-bar** [comment]
Will try to get to it later today
