### ISSUE TITLE
New version stops working with Mey Modiin

### ISSUE THREAD

**Issue by yalmog99** [maorcc/citymind_water_meter#33]
Hi,
After upgrading to the latest version, the intergration stops working with Mey Modiin.
I n the log I get:
Failed to post JSON to https://api.city-mind.com/consumer/login, HTTP Status: Bad Request (400)

Failed to load select for None Alert #23, Error: 'NoneType' object is not iterable, Line: 207
Failed to load select for None Alert #1001, Error: 'NoneType' object is not iterable, Line: 207
Failed to load sensor for None Messages, Error: object of type 'NoneType' has no len(), Line: 268
Failed to load sensor for None Alerts, Error: object of type 'NoneType' has no len(), Line: 306
Failed to load sensor for None Vacations, Error: object of type 'NoneType' has no len(), Line: 344

Can you help ?
What's the solution ?

**Comment by yalmog99** [comment]
No, I didn't know I should.
I have my old account here: https://cp.city-mind.com/
Should I open somewhere else ? Should I reinstall the intergration ?

**Comment by yalmog99** [comment]
Thanks.
I created an account at: https://rym-pro.com/#/
I have a username (email) and password.
I updated them in the integration configuration (thats what I assume I need to do, no titles there).
Should I see new entities at home assistant ? 
I don't think I see.

**Comment by yalmog99** [comment]
Update:
After restarting Home assistant, I got the new entities.
Thanks !

**Comment by elad-bar** [comment]
Great, thanks for the update
