### ISSUE TITLE
can't rename meter device to a meaningful name

### ISSUE THREAD

**Issue by arnonsha** [maorcc/citymind_water_meter#39]
I have a multiple meter account, and trying to rename the meter device and give it a meaningful name, rather than stick with the meter serial number:

![image](https://user-images.githubusercontent.com/35176391/200601351-b4e9edf3-c7b4-4567-84ca-197158a3a061.png)

The new device name is kept some time for some time (not sure if it's hours or days),after which it is overrun by the original name with the serial number. Is that the add on or homeassistant responsible for this behavior ?

**Comment by robic77** [comment]
Similar issue for me. I change the icons for some entities, but thay revert to default after few days (never happened with other integrations)

**Comment by elad-bar** [comment]
you can change the device name and it will update nested entity's names, pls let me know if it works for you

thanks

**Comment by arnonsha** [comment]
Thanks @elad-bar 
It works. Modified name 2 days ago, and it hadn't change back. Closing the issue
