### ISSUE TITLE
multiple meters are not supported

### ISSUE THREAD

**Issue by arnonsha** [maorcc/citymind_water_meter#4]
Hi and thank you for this addon

Can your addon handle more than one meter ? 

**When I log into my citymind account using a browser:**
I get a list of all my meters (I live in a מושב, so I have more than one). I then need to choose one, and only then I'd get that particular meter consumption information. See image:

![water Annotation 2020-08-01 095152](https://user-images.githubusercontent.com/35176391/89096146-ef57dc80-d3dc-11ea-8026-d4973e82aaca.png)

**Using the addon**
I see 2 entities only (Water Meter Reading and Water Consumption), probably of one meter onlt. I believe this is because I have more than one meter. When looking at the HA log files, I see the following error:

`2020-08-01 00:06:18 ERROR (SyncWorker_5) [custom_components.citymind_water_meter.sensor] Data from server contains an empty #cphMain_div_properties tag:`

After the error message I see the html core returned from the citymind page in the log file

**Comment by maorcc** [comment]
Thank you @arnonsha for the detailed issue reporting.
Supporting multiple meters is possible, but for that, I would need access to an account that has multiple meters.
Also, I'm not sure that it is worth the effort of maintaining this feature if it is just for one user (you).  I suggest that if more people will vote for this feature, then we will implement support for it.

We also need to take into consideration that Arad Technologies are rewriting the City-Mind service, and so we would probably need to rewrite this integration 6 months from now.

**Comment by arnonsha** [comment]
Thanks @maorcc 
In case there are more votes and you decide to implement, I can give you my account details.

**Comment by yuvalabou** [comment]
> Thank you @arnonsha for the detailed issue reporting.
> Supporting multiple meters is possible, but for that, I would need access to an account that has multiple meters.
> Also, I'm not sure that it is worth the effort of maintaining this feature if it is just for one user (you). I suggest that if more people will vote for this feature, then we will implement support for it.
> 
> We also need to take into consideration that Arad Technologies are rewriting the City-Mind service, and so we would probably need to rewrite this integration 6 months from now.

It maybe worth checking if they will have an API?

**Comment by elad-bar** [comment]
@yuvalabou can you post saved html file after login (pls mask private details)?

Thanks

**Comment by elad-bar** [comment]
Added in v2.0.0, will be released soon

**Comment by maorcc** [comment]
Fixed in v2.0.0 #29

**Comment by arnonsha** [comment]
Works like a charm !
Thank you all.for adding this feature.

**Comment by elad-bar** [comment]
@arnonsha can you pls enable store debug data switch so it will create json file in ha config directory (within it there should be .storage directory, debug file will be there) and post it (after cleaning sensitive data) just to make sure sensors are being created correctly? 

Thanks

**Comment by arnonsha** [comment]
OK,
I do see wrong numbers. Will open a new issue
