### ISSUE TITLE
Renaming project to "Read Your Meter Pro"

### ISSUE THREAD

**Issue by maorcc** [maorcc/citymind_water_meter#51]
Citymind web service name has changed to "Read Your Meter Pro", so we want to change the name of this integration to reflect the new name.
This issue is for tracking the efforts of renaming the project.

After renaming the project, we will work on making this integration an official Home Assistant integration as described here: #50.

**Comment by elad-bar** [comment]
that name is already taken, nothing to do with it,
rename the component will be only once the official one will get released fully
