### ISSUE TITLE
הוספת אפשרות המרה 

### ISSUE THREAD

**Issue by The-cpu-max** [maorcc/citymind_water_meter#55]
היי 
הייתי שמח אם הייתם מוסיפים אפשרות לדעת כמה יוצא העלות בזמן אמת לפי המחיר הקיים של המים 
תוך חישוב ליטר הקוב שצרכתי עד כה מתחילת החודש

**Comment by elad-bar** [comment]
היי,
מכיוון שהמחיר משתנה לפי הרשות הרלוונטית, אין אפשר לייצר באופן אוטמטי משיכה, אלא אם אתה מכיר api רלוונטי,
האינטגרציה תומכת הגדרת מחיר גבוה נמוך ודמי ביוב לקוב כולל הגדרה של כמה קוב לפני מספר נפשות בתעריף הנמוך על ידי שירות, מידע איך להגדיר זמין בדף הראשי

**Comment by elad-bar** [comment]
אלא אם התכוונת להוסיף עוד חיישן שסוכם, ואז יש שתי אפשרויות דרך ha לבצע את זה ואחת דרך grafana:
דרך ניהול אנרגיה
לייצר חיישן אגרגצינ
ב grafana לבצע חישוב על הדאטא שמוזרם דרך influx, prometheus or mysql

**Comment by The-cpu-max** [comment]
> היי, מכיוון שהמחיר משתנה לפי הרשות הרלוונטית, אין אפשר לייצר באופן אוטמטי משיכה, אלא אם אתה מכיר api רלוונטי, האינטגרציה תומכת הגדרת מחיר גבוה נמוך ודמי ביוב לקוב כולל הגדרה של כמה קוב לפני מספר נפשות בתעריף הנמוך על ידי שירות, מידע איך להגדיר זמין בדף הראשי

מובן , ישנה אפשרות להוספת המרה לליטרים ? לצד קוב?

**Comment by elad-bar** [comment]
ביוכלת המובנת של ha אפשר להמיר מידות בהגדרות של הרכיבים, אני אנסה יותר מאוחר לבדוק איך לעשות את זה

**Comment by The-cpu-max** [comment]
> ביוכלת המובנת של ha אפשר להמיר מידות בהגדרות של הרכיבים, אני אנסה יותר מאוחר לבדוק איך לעשות את זה

זה יהיה ממש מעולה . לגבי API למיתב אין אז זה ממש בעייתי עבורי . אני אשמח שתהיה אפשרות להזין את התעריף בצורה ידנית ושהוא יחשב לבד . מחירי המים בדרך כלל נשארים יציבים אחת לכמה חודשים

**Comment by elad-bar** [comment]
יש אפשרות דרך סרוויס ב ha לעדכן את התעריפים, לבנות ולתחזק תעריפי מים בקובץ זה משהו שאני פחות בעד, אבל אני אנסה למצוא איזה api כזה כשיהיה קצת זמן לעבוד על זה

**Comment by elad-bar** [comment]
סוגר, אין אפשרות לעקוב אחרי כל רשות, ברשויות מסויימות יש שני ספקי מים כך שזה הופך את זה ליותר מורכב
