### ISSUE TITLE
Only one entity

### ISSUE THREAD

**Issue by hadyos** [maorcc/citymind_water_meter#56]
I'm not sure if it's a bug but I'm seeing only one entity (sensor.meter_{METER_ID}_total_consumption),
Is it normal or I have to add the other device entities manually ?

**Comment by elad-bar** [comment]
Sound bit weird, how did you install it? What version of HA and integration?

**Comment by hadyos** [comment]
All latest, HA and integration
Install it through HACS, typed in my email and password install it and this what I got right away.

**Comment by hadyos** [comment]
That's my log

Thanks

**Comment by hadyos** [comment]
looking at the debug file I see (MainThread) [homeassistant.components.rympro.coordinator] Error fetching rympro data: <ClientResponse(https://api-ctm.city-mind.com/consumption/last-read) [401 Unauthorized]>

Maybe that's the problem ?

**Comment by elad-bar** [comment]
you are using a fork of this component, to make it official in HA,
if you would like to use the custom component available here, please follow the instructions - as you can see the component name is `homeassistant.components.rympro.coordinator` while custom component are being represented differently in logs (also available in README)

**Comment by elad-bar** [comment]
to add the right component that support to full functionality - add `CityMind Water Meter` not `Read Your Meter Pro`

**Comment by hadyos** [comment]
I don't understand, I installed this integration through HACS just like it
mentioned in the README in github, Is there another way to install it that
I'm not aware of ?

Thanks
hadyos

**Comment by hadyos** [comment]
I don't see any City-Mind Water Meter in HACS but I do see  Read Your Meter Pro

**Comment by elad-bar** [comment]
Please add this repo as custom repo in hacs, once you will do that, it will be available

**Comment by hadyos** [comment]
What repo? what is name of repo and how do I get it?

**Comment by elad-bar** [comment]
This repository

https://hacs.xyz/docs/faq/custom_repositories/
