### ISSUE TITLE
When installing using HACS, it's the wrong version.

### ISSUE THREAD

**Issue by yuvalabou** [maorcc/citymind_water_meter#6]
although its installing 1.4, the version installed is actually the one before all the work @elad-bar did.
why is that?

**Comment by yuvalabou** [comment]
Just saying - you need to choose 'master' version and not 'latest'
Thanks!

**Comment by maorcc** [comment]
It is because I didn't yet create a new release with Elad's code.  It obviously has breaking changes. I'll finish testing and then I'll create a 2.0 release with instructions.
