### ISSUE TITLE
Move to async methods

### ISSUE THREAD

**Issue by GuyKh** [maorcc/citymind_water_meter#61]
As written in the logs:
```
2024-05-07 11:18:04.469 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/citymind_water_meter/core/managers/home_assistant.py", line 183, in _update_data_providers
    self._hass.async_create_task(self.async_update_data_providers())
  File "/usr/src/homeassistant/homeassistant/core.py", line 816, in async_create_task
    self.verify_event_loop_thread("async_create_task")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'citymind_water_meter' calls async_create_task from a thread at custom_components/citymind_water_meter/core/managers/home_assistant.py, line 183: self._hass.async_create_task(self.async_update_data_providers()). Please report it to the author of the 'citymind_water_meter' custom integration.
```

calls to `async_create_task` are not being awaited.
Should make all the functions async-await.

**Comment by elad-bar** [comment]
Which version of integration are you using?

**Comment by GuyKh** [comment]
@elad-bar - the latest - 2.0.12.
But also looking at the code - the async calls are done synchroneously
[example](https://github.com/maorcc/citymind_water_meter/blob/890e282464c311cdf0a827a11f9ffbc1f4db942f/custom_components/citymind_water_meter/core/models/base_entity.py#L107)
[example](https://github.com/maorcc/citymind_water_meter/blob/890e282464c311cdf0a827a11f9ffbc1f4db942f/custom_components/citymind_water_meter/core/components/switch.py#L25)
[example](https://github.com/maorcc/citymind_water_meter/blob/890e282464c311cdf0a827a11f9ffbc1f4db942f/custom_components/citymind_water_meter/core/managers/home_assistant.py#L77C24-L77C41)
[example](https://github.com/maorcc/citymind_water_meter/blob/890e282464c311cdf0a827a11f9ffbc1f4db942f/custom_components/citymind_water_meter/component/managers/home_assistant.py#L854)

**Comment by elad-bar** [comment]
Latest is 2.0.14 and it fixes that issue, pls check and update

Thanks

**Comment by GuyKh** [comment]
Thanks @elad-bar - it seems that HACS didn't update the latest.

**Comment by elad-bar** [comment]
Great... happens to HACS sometimes :)
