### ISSUE TITLE
invalid_server_details

### ISSUE THREAD

**Issue by vladeha** [maorcc/citymind_water_meter#62]
After my HA was updated to latest 2024.5.4 version, integration stopped working..
I got error "invalid_server_details".
Tried re-configure it, remove and add, no luck.
With same email and password I can login to https://rym-pro.com site without problem.
In HACS my integration version was v2.0.14 , I've downloaded master 890e282, still no luck.
When I tried to add integration(after downloading master version in hacs and restarting HA) I got several  different errors:
 "Source: custom_components/citymind_water_meter/config_flow.py:69 . Failed to create integration, Error: 
invalid_server_details"
another error:
"Source: custom_components/citymind_water_meter/component/api/api.py:374
integration: CityMind Water Meter
Failed to access API
Invalid credentials, Error #5060: Email and/or password are not valid

another error.
Failed to post JSON to https://api.city-mind.com/consumer/login, HTTP Status: Too Many Requests (429), Data: {'error': 'Unauthorized request, user request rate exceeded limit.', 'code': 429}
But again with same credentials I can log in to website without errors(actually I still logged in and see my water consumption on the web site)

**Comment by maorcc** [comment]
Arad again has changed the URL of their backend service from 
https://api-ctm.city-mind.com"
to:
https://eu-customerportal-api.harmonyencoremdm.com/v1.1

See https://github.com/OnFreund/pyrympro/compare/v0.0.7...v0.0.8

**Comment by elad-bar** [comment]
I'm currently abroad, will try to get to it during the weekend,
If you have solution, please do a PR

Thanks

**Comment by Arielgordon123** [comment]
Hi
its my first day with HA and Iv'e found this issue
I would like to help with this

**Comment by vladeha** [comment]
Hi, your help will be appreciated ,if you can, please do a PR ) Currently authentication failing , because of backend service was changed.

**Comment by vladeha** [comment]
[Arielgordon123] Thank you! It works)
