### ISSUE TITLE
Add GitHub Actions for running tests on pull requests

### ISSUE THREAD

**Issue by Arielgordon123** [maorcc/citymind_water_meter#64]
#### Problem
Currently, this project does not have a GitHub Actions workflow set up to automatically run tests on pull requests. This can lead to bugs and regressions slipping into the codebase, as changes are not being tested automatically before they are merged.

#### Proposed Solution
Set up a GitHub Actions workflow that runs the project's existing test suite (e.g., unit tests, integration tests) on every pull request. This will ensure that all code changes are properly tested before they are merged, catching potential issues early in the development process.

**Comment by elad-bar** [comment]
added as part of #79

**Comment by elad-bar** [comment]
Added actions for PR
