### ISSUE TITLE
Cannot add the integration - getting unknown error message 

### ISSUE THREAD

**Issue by drorya1** [maorcc/citymind_water_meter#70]
Integration stopped working 
I removed the integration and added it again .
While it is installed in HACS , when I try to add it to Integration I get "unknown error occurred"
I validated and this is the exact same PWD used in https://rym-pro.com/#/

![chrome_FRNRVTu6dp](https://github.com/maorcc/citymind_water_meter/assets/79847067/11c31a88-9d0a-4e3e-ae67-26d7a27205cf)

**Comment by elad-bar** [comment]
Do you have logs to share (debug log level)?
Did you remove it from HA or HACS? Did you restart the HA in between?

Thanks

**Comment by drorya1** [comment]
There are no logs as apparently the integration is installed on Hacs but is
not installed as integartion.
I added the debug to logger but could not find anything related to it .
I have removed it from HACS and from Integration as well as removed old
integration which was still there ( by removing the directory from custom
components )
Next step would be to restore a backup to see if this is solved .
I rebooted in between

**Comment by eyalcha** [comment]
@elad-bar 
Don't know if it is the same issue, but I fail to connect
<img width="410" alt="image" src="https://github.com/maorcc/citymind_water_meter/assets/64679987/30d05acb-1373-4495-93d8-9df85a9c96c4">

**Comment by elad-bar** [comment]
Without logs I cannot assist

**Comment by elad-bar** [comment]
Please follow the next steps and share the resilt:
- Remove integration
- Uninstall integration from HACS
- Restart HA
- Make sure integration is not installed
- Install from HACS
- Add logger section to enable debug logs as in README 
- Restart HA
- Set up integration
- If still not working, share logs

Please note that integration name is citymind not read your meter pro, in addition, please state you HA version

Thanks
-

**Comment by elad-bar** [comment]
@eyalcha you have tried to set up read your meter pro which is official integration based on this repo but still WIP

Please report the issue in HA core repo.

Thanks

**Comment by arnonsha** [comment]
addon also doesn't load for me.

![image](https://github.com/maorcc/citymind_water_meter/assets/35176391/872e660b-959b-4d68-b195-6a187f457e1c)


In core log file I see the following:
`2024-06-02 21:32:00.767 ERROR (MainThread) [custom_components.citymind_water_meter] Failed to load CityMind, error: , line: 36`

**Comment by drorya1** [comment]
Just to mention I just rolled back to 30May backup and it seems to be
working now.
I suspect something with the update might be buggy .
I will share more feedback if I see that there are errors or malfunction .

**Comment by elad-bar** [comment]
@arnonsha did you set debug log level? Did you follow the steps for clean install?

@drorya1 I guess you are on v2.0.15 now, is that correct?
Can you enable debug logs (from logger component not ui) and upgrade again?
You can revert to previous versions using hacs (redownloaf) no need to restore backup

Thanks

**Comment by elad-bar** [comment]
will update documentation and make it clearer

It means that encryption key was modified from outside the code, Please remove the integration and re-add it to make it work again.

if still not working, remove the integration (from devices & service not hacs) again, in /config/.storage directory remove files contains `citymind`, restart and set up integration again

**Comment by mikeage** [comment]
I'm afraid that wasn't enough. I updated again to 3.0.3, removed the integration, deleted these two files:
```
.storage/.citymind_water_meter
.storage/citymind_water_meter.9b1ce813b6d085b692e806fa39d61bec.config.json
```
And then tried adding it again. Failed with:
```
2024-06-03 11:51:52.801 INFO (MainThread) [custom_components.citymind_water_meter.managers.flow_manager] Config flow started, Step: user, Input: None
2024-06-03 11:52:03.740 INFO (MainThread) [custom_components.citymind_water_meter.managers.flow_manager] Config flow started, Step: user, Input: {'email': 'XXXXX', 'password': 'XXXXX'}
2024-06-03 11:52:03.740 INFO (MainThread) [custom_components.citymind_water_meter.managers.config_manager] loaded: None
2024-06-03 11:52:03.741 INFO (MainThread) [custom_components.citymind_water_meter.managers.config_manager] default_configuration: {'meters': {}}
2024-06-03 11:52:03.741 INFO (MainThread) [custom_components.citymind_water_meter.managers.config_manager] adding meters
2024-06-03 11:52:03.741 INFO (MainThread) [custom_components.citymind_water_meter.managers.config_manager] updated
  File "/config/custom_components/citymind_water_meter/config_flow.py", line 36, in async_step_user
  File "/config/custom_components/citymind_water_meter/managers/flow_manager.py", line 69, in async_step
  ```

**Comment by drorya1** [comment]
@Elad bar
Indeed I am on 2.0.15 tried to update to 3.0.3 and the integration does not
work
Unfortunately I cannot roll back see attached clip I will try to delete
mannually

**Comment by drorya1** [comment]
[config_entry-hacs-4f0fd37a37158caccbd39a15b513591b.json](https://github.com/user-attachments/files/15533588/config_entry-hacs-4f0fd37a37158caccbd39a15b513591b.json)

https://github.com/maorcc/citymind_water_meter/assets/79847067/6a096637-d0cf-49c3-a39c-2a82cdd95d40

**Comment by drorya1** [comment]
@elad-bar 
Reverting back to 2.0.15 restores the service

**Comment by Arielgordon123** [comment]
It's happened to me too when upgrading from 2.0.15 to 3.0.3

**Comment by elad-bar** [comment]
Did you try what I wrote above?

**Comment by Fannangir** [comment]
I see the same issue.

**Comment by elad-bar** [comment]
is it still relevant?

thanks

**Comment by arnonsha** [comment]
I removed and reinstalled. Solved my problem 
I also see that the meter name now also contains the full name and not just the meter number which is very helpful (I have few meters)

**Comment by Fannangir** [comment]
Issue solved by reinstalling the integration.
Thank you very much.

**Comment by mikeage** [comment]
I can also confirm that removing and reinstalling was required, but fixed the issue for me as well. Just doing a "reload" or even "(re-)configure"  after upgrading to 3.0.5 was insufficient.

**Comment by drorya1** [comment]
Working for me as well
