### ISSUE TITLE
Duplicate Entities name

### ISSUE THREAD

**Issue by hadyos** [maorcc/citymind_water_meter#75]
Setting up CityMind Water meter addon gives me 2 devices although I have only one water meter and because of that i get  duplicate entities name all over with only device name distinguished...

**Comment by elad-bar** [comment]
Can you pls share diagnostics file?

Thanks

**Comment by hadyos** [comment]
[home-assistant_citymind_water_meter_2024-06-24T16-25-39.323Z.log](https://github.com/user-attachments/files/15958610/home-assistant_citymind_water_meter_2024-06-24T16-25-39.323Z.log)

**Comment by elad-bar** [comment]
You have uploaded log file, can you pls share diagnostics file?

**Comment by hadyos** [comment]
[config_entry-citymind_water_meter-2dd3f98a39e335eb7c31ae9fd84c1fc6.json](https://github.com/user-attachments/files/15960159/config_entry-citymind_water_meter-2dd3f98a39e335eb7c31ae9fd84c1fc6.json)

**Comment by elad-bar** [comment]
According to the diagnostics file, seems all working according to design and as described in the README page,
You have one device for the account with entities related to it and one device for your meter with the entities of it,
Can you please share a screenshot describing the issue?

Thanks

**Comment by hadyos** [comment]
!
![Screenshot_20240625_122128](https://github.com/maorcc/citymind_water_meter/assets/11536897/da6f7c71-1431-4bf1-be57-f4308038228e)
![Screenshot_20240625_120212](https://github.com/maorcc/citymind_water_meter/assets/11536897/c6ca1c00-2304-413b-a60d-efba7e552192)

**Comment by elad-bar** [comment]
not sure i understand where are the duplicate entities

**Comment by hadyos** [comment]
The attached screenshot will show exactly what I mean. Why do I have High Rate Cost twice. Of course there are other entities with same problem
![Screenshot_20240625_125120](https://github.com/maorcc/citymind_water_meter/assets/11536897/d45db392-f045-45a9-9643-ca3de4dc10fa)

**Comment by elad-bar** [comment]
have you noticed that one is sensor and the other is number?
number is to configure, sensor is for energy component (which is not supporting number entity)

closing the issue
